# Copyright 2022 Mattermost, Inc.
name: "plugin-ci/setup"
description: |
  This action used to setup the CI env for Mattermost Plugins

  **Note**
  Note that if an `.nvmrc` file is present in the plugin project's root
  directory, this file will be used to determine what version of node to install for CI.

inputs:
  golangci-lint-version:
    default: v1.49.0
    description: |
      The version to use for golangci-lint
    required: false

runs:
  using: "composite"
  steps:
    - name: Install Node
      uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
      with:
        node-version-file: ".nvmrc"
        cache: "npm"
        cache-dependency-path: webapp/package-lock.json

    - name: Install golangci-lint
      shell: bash
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${{ inputs.golangci-lint-version }}
