# Copyright 2022 Mattermost, Inc.
name: "plugin-ci/setup"
description: |
  This action used to setup the CI env for Mattermost Plugins

  **Note**
  Note that if an `.nvmrc` file is present in the plugin project's root
  directory, this file will be used to determine what version of node to install for CI.

inputs:
  go-version-file:
    default: go.mod
    description: |
      Path to the file that declares the Go version
    required: false

  golangci-lint-version:
    default: v1.52.2
    description: |
      The version to use for golangci-lint
    required: false

runs:
  using: "composite"
  steps:
    - name: check-if-plugin-has-webapp
      id: webapp_check
      shell: bash
      run: |
        if [ -d "webapp" ]; then
          echo "exist=true" >> $GITHUB_OUTPUT
        else
          echo "exist=false" >> $GITHUB_OUTPUT
        fi

    - name: install-node
      if: steps.webapp_check.outputs.exist == 'true'
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version-file: ".nvmrc"
        cache: "npm"
        cache-dependency-path: webapp/package-lock.json

    - name: setup-go
      uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
      with:
        go-version-file: ${{ inputs.go-version-file }}

    - name: install-golangci-lint
      shell: bash
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${{ inputs.golangci-lint-version }}
