# Copyright 2022 Mattermost, Inc.
name: "mattermost/update-commit-status"
description: "An action that updates the commit status"

inputs:
  repository_full_name:
    description: "The full name of the repository"
    required: true
  commit_sha:
    description: "The sha of the commit to update the status"
    required: true
  context:
    description: "The context name of the status check"
    required: true
  description:
    description: "The description of the status check"
    required: true
  status:
    description: "The state of the status check"
    required: true
  target_url:
    description: "The target url of the status check"
    required: false

runs:
  using: composite
  steps:
    - name: ci/update-commit-status
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # 7.0.1
      env:
        REPOSITORY_FULL_NAME: ${{ inputs.repository_full_name }}
        SHA: ${{ inputs.commit_sha }}
        CONTEXT: ${{ inputs.context }}
        DESCRIPTION: ${{ inputs.description }}
        STATUS: ${{ inputs.status }}
      with:
        github-token: ${{ env.GITHUB_TOKEN }}
        script: |
          try {
            var { REPOSITORY_FULL_NAME, SHA, CONTEXT, DESCRIPTION, STATUS } = process.env;
            var TARGET_URL = core.getInput('target_url', { required: false });

            if (TARGET_URL) {}
            else { 
              var TARGET_URL = "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}";
            }

            await github.rest.repos.createCommitStatus({
              owner: REPOSITORY_FULL_NAME.split("/")[0],
              repo: REPOSITORY_FULL_NAME.split("/")[1],
              sha: SHA,
              context: CONTEXT,
              description: DESCRIPTION,
              state: STATUS,
              target_url: TARGET_URL
            });
            core.info(`Updated build status with ${STATUS} for commit ${SHA} on ${REPOSITORY_FULL_NAME}`);
          } catch (err) {
            core.error(`Failed to update build status with ${STATUS} for commit ${SHA} on ${REPOSITORY_FULL_NAME}`);
            core.setFailed(`Action failed with error: ${err}`);
          }
